### ISSUE TITLE
Installation fails with gcc-related error

### ISSUE THREAD

**Issue by amckiern** [Nexedi/dream#2]
Hi, 
I have just tried to install DREAM using the "python setup.py install" command but it fails with an error about gcc.

I am on Windows 7, with Python 2.7.5 installed.

Here's a snapshot of the error:

![dream_011](https://cloud.githubusercontent.com/assets/8472772/10332695/e3d1f89a-6cd6-11e5-9521-79e82f54e78a.jpg)

Has anyone else had this issue and resolved it?

Thanks,
Adrian.

**Comment by GeorgiosDagkakis** [comment]
Hi Adrian,

it seems to be a missing dependency, maybe mysql development version, maybe gcc itself. Hard to tell from that screenshot. 

I would suggest to hack setup.py to remove MySQL-python dependency (remove https://github.com/Nexedi/dream/blob/master/setup.py#L23 ) because it is not a strong dependency. Can you try this, run the setup again and tell me if it works?

Thanks,
George

**Comment by amckiern** [comment]
Hi George, thanks for the reply.

I did what you suggested, and it got past that point, but then there were a load of syntax errors and an issue where it could not find R in the PATH variable, probably because I didn't have R installed :)
I have tried to attach the log from that attempt but Github seems to be unable to process it.

Then I installed R and added the path to the 64-bit version it to the system path variable and tried installing again. This time it got as far as starting R but then failed.

Here is an excerpt from that attempt:

```
Installed c:\program files\anaconda\lib\site-packages\dream-0.0.1-py2.7.egg
Processing dependencies for dream==0.0.1
Searching for rpy2
Reading http://pypi.python.org/simple/rpy2/
Best match: rpy2 2.7.0
Downloading https://pypi.python.org/packages/source/r/rpy2/rpy2-2.7.0.tar.gz#md5=afd9ea81a03640b60240b7d53518e652
Processing rpy2-2.7.0.tar.gz
Writing c:\users\amckiern\appdata\local\temp\easy_install-lzrks5\rpy2-2.7.0\setup.cfg
Running rpy2-2.7.0\setup.py -q bdist_egg --dist-dir c:\users\amckiern\appdata\local\temp\easy_install-lzrks5\rpy2-2.7.0\egg-dist-tmp-r8c0u8
R version 3.2.2 (2015-08-14) -- "Fire Safety"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
http://www.gnu.org/licenses/.

R version 3.2.2 (2015-08-14) -- "Fire Safety"
c:\PROGRA~1\r\R-32~1.2\bin\x64\R CMD config --ldflags
'sh' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    test_suite='dream.tests'
  File "C:\Program Files\Anaconda\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "C:\Program Files\Anaconda\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\Anaconda\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Program Files\Anaconda\lib\site-packages\setuptools\command\install.py", line 73, in run
    self.do_egg_install()
  File "C:\Program Files\Anaconda\lib\site-packages\setuptools\command\install.py", line 101, in do_egg_install
    cmd.run()
  File "C:\Program Files\Anaconda\lib\site-packages\setuptools\command\easy_install.py", line 360, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\Program Files\Anaconda\lib\site-packages\setuptools\command\easy_install.py", line 584, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "C:\Program Files\Anaconda\lib\site-packages\setuptools\command\easy_install.py", line 636, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\Program Files\Anaconda\lib\site-packages\setuptools\command\easy_install.py", line 688, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "C:\Program Files\Anaconda\lib\site-packages\pkg_resources.py", line 586, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "C:\Program Files\Anaconda\lib\site-packages\pkg_resources.py", line 831, in best_match
    return self.obtain(req, installer) # try and download/install
  File "C:\Program Files\Anaconda\lib\site-packages\pkg_resources.py", line 843, in obtain
    return installer(requirement)
  File "C:\Program Files\Anaconda\lib\site-packages\setuptools\command\easy_install.py", line 604, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "C:\Program Files\Anaconda\lib\site-packages\setuptools\command\easy_install.py", line 634, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "C:\Program Files\Anaconda\lib\site-packages\setuptools\command\easy_install.py", line 829, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "C:\Program Files\Anaconda\lib\site-packages\setuptools\command\easy_install.py", line 1109, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Program Files\Anaconda\lib\site-packages\setuptools\command\easy_install.py", line 1095, in run_setup
    run_setup(setup_script, args)
  File "C:\Program Files\Anaconda\lib\site-packages\setuptools\sandbox.py", line 33, in run_setup
    lambda: execfile(
  File "C:\Program Files\Anaconda\lib\site-packages\setuptools\sandbox.py", line 81, in run
    return func()
  File "C:\Program Files\Anaconda\lib\site-packages\setuptools\sandbox.py", line 35, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 291, in <module>

  File "setup.py", line 198, in getRinterface_ext

  File "setup.py", line 151, in cmd_config

  File "C:\Program Files\Anaconda\lib\subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('c:\\PROGRA~1\\r\\R-32~1.2\\bin\\x64\\R', 'CMD', 'config', '--ldflags')' returned non-zero exit status 1

```

Thanks,
Adrian.

**Comment by GeorgiosDagkakis** [comment]
Hi,

one thing I can propose is to comment also RPY2 https://github.com/Nexedi/dream/blob/master/setup.py#L20 dependency. Then you would not have access to KE tool facilities though. But you should be able to run ManPy as simulation.

Please try this and tell me, we would look also at the issue. We plan to provide separate Python eggs for DREAM modules in the future, so this would be easier for users that want to use only part of the project.

Thanks,
George

**Comment by amckiern** [comment]
Hi George,

I removed rpy2 and ran the setup and got the error below:

```
Processing dream-0.0.1-py2.7.egg
removing 'c:\program files\anaconda\lib\site-packages\dream-0.0.1-py2.7.egg' (and everything under it)
creating c:\program files\anaconda\lib\site-packages\dream-0.0.1-py2.7.egg
Extracting dream-0.0.1-py2.7.egg to c:\program files\anaconda\lib\site-packages
dream 0.0.1 is already the active version in easy-install.pth
Installing dream_simulation-script.py script to C:\Program Files\Anaconda\Scripts
Installing dream_simulation.exe script to C:\Program Files\Anaconda\Scripts
Installing dream_platform-script.py script to C:\Program Files\Anaconda\Scripts
Installing dream_platform.exe script to C:\Program Files\Anaconda\Scripts

Installed c:\program files\anaconda\lib\site-packages\dream-0.0.1-py2.7.egg
Processing dependencies for dream==0.0.1
Searching for zope.dottedname
Reading http://pypi.python.org/simple/zope.dottedname/
Best match: zope.dottedname 4.1.0
Downloading https://pypi.python.org/packages/source/z/zope.dottedname/zope.dottedname-4.1.0.tar.gz#md5=503ed09f1a3675e8c413cba81c79da4e
Processing zope.dottedname-4.1.0.tar.gz
Writing c:\users\amckiern\appdata\local\temp\easy_install-vrtpgv\zope.dottedname-4.1.0\setup.cfg
Running zope.dottedname-4.1.0\setup.py -q bdist_egg --dist-dir c:\users\amckiern\appdata\local\temp\easy_install-vrtpgv\zope.dottedname-4.1.0\egg-dist-tmp-3jsg4p
Adding zope.dottedname 4.1.0 to easy-install.pth file

Installed c:\program files\anaconda\lib\site-packages\zope.dottedname-4.1.0-py2.7.egg
Searching for pydot
Reading http://pypi.python.org/simple/pydot/
Reading http://code.google.com/p/pydot/
Reading http://dkbza.org/pydot.html
error: An established connection was aborted by the software in your host machine
```

I then tried again and got: 

```
creating build\bdist.win-amd64\egg\EGG-INFO
copying dream.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying dream.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying dream.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying dream.egg-info\entry_points.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying dream.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG-INFO
copying dream.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying dream.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
creating 'dist\dream-0.0.1-py2.7.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing dream-0.0.1-py2.7.egg
removing 'c:\program files\anaconda\lib\site-packages\dream-0.0.1-py2.7.egg' (and everything under it)
creating c:\program files\anaconda\lib\site-packages\dream-0.0.1-py2.7.egg
Extracting dream-0.0.1-py2.7.egg to c:\program files\anaconda\lib\site-packages
dream 0.0.1 is already the active version in easy-install.pth
Installing dream_simulation-script.py script to C:\Program Files\Anaconda\Scripts
Installing dream_simulation.exe script to C:\Program Files\Anaconda\Scripts
Installing dream_platform-script.py script to C:\Program Files\Anaconda\Scripts
Installing dream_platform.exe script to C:\Program Files\Anaconda\Scripts

Installed c:\program files\anaconda\lib\site-packages\dream-0.0.1-py2.7.egg
Processing dependencies for dream==0.0.1
Searching for pydot
Reading http://pypi.python.org/simple/pydot/
Reading http://code.google.com/p/pydot/
Reading http://dkbza.org/pydot.html
Best match: pydot 1.0.28
Downloading http://pydot.googlecode.com/files/pydot-1.0.28.tar.gz
Processing pydot-1.0.28.tar.gz
Writing c:\users\amckiern\appdata\local\temp\easy_install-thl9vj\pydot-1.0.28\setup.cfg
Running pydot-1.0.28\setup.py -q bdist_egg --dist-dir c:\users\amckiern\appdata\local\temp\easy_install-thl9vj\pydot-1.0.28\egg-dist-tmp-rynudl
Couldn't import dot_parser, loading of dot files will not be possible.
zip_safe flag not set; analyzing archive contents...
Adding pydot 1.0.28 to easy-install.pth file

Installed c:\program files\anaconda\lib\site-packages\pydot-1.0.28-py2.7.egg
Searching for SimPy>=3
Reading http://pypi.python.org/simple/SimPy/
Best match: simpy 3.0.8
Downloading https://pypi.python.org/packages/source/s/simpy/simpy-3.0.8.tar.gz#md5=477552f5bf81d8d293b3e2bb8668e406
Processing simpy-3.0.8.tar.gz
Writing c:\users\amckiern\appdata\local\temp\easy_install-qx8zrj\simpy-3.0.8\setup.cfg
Running simpy-3.0.8\setup.py -q bdist_egg --dist-dir c:\users\amckiern\appdata\local\temp\easy_install-qx8zrj\simpy-3.0.8\egg-dist-tmp-xlg5c4
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*' found under directory 'docs\_build'
warning: no previously-included files matching '*' found under directory 'docs\__pycache__'
zip_safe flag not set; analyzing archive contents...
simpy.util: module references __file__
simpy.__init__: module references __path__
Adding simpy 3.0.8 to easy-install.pth file

Installed c:\program files\anaconda\lib\site-packages\simpy-3.0.8-py2.7.egg
error: Installed distribution pyparsing 2.0.3 conflicts with requirement pyparsing<=1.9.9
```

I uninstalled pyparsing 2.0.3 and tried again, but that time it went to find the best pyparsing version and downloaded 2.0.3 again! So, in setup.py I changed the pyparsing requirement to say "pyparsing<2", and it installed pyparsing 1.5.7...

The install seemed to work that time, but I need to go to a meeting now, and will test it later...

**Comment by GeorgiosDagkakis** [comment]
this is nice, tell me if it works when you test

**Comment by jerome-nexedi** [comment]
I remember that pulp-or specify a pyparsing version in its setup.py 
We did that 
jerome-nexedi/pulp-or@101c394eb2737e9997b9d9e329886b1d301e7038

Installing with `pip install` is not really supposed to work at this stage. We made SlapOS profiles for installation. Please take refer to https://github.com/SlapOS/slapos/blob/master/software/dream/software.cfg

**Comment by jerome-nexedi** [comment]
We are not really using github for issues / merge requests, this github is just a mirror. If you like to discuss further, I would suggest you file issue on https://lab.nexedi.com/nexedi/dream/

We are disabling issues on github now, thanks.
